[package]
name = "cabinet"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "cabinet-simulation",
]

[workspace.dependencies]
foundationdb = { git = "https://github.com/foundationdb-rs/foundationdb-rs.git", rev = "7ea683975f0069776c74342f326ecfa001cc1a73", features = ["fdb-7_4"] }
foundationdb-simulation = { git = "https://github.com/foundationdb-rs/foundationdb-rs.git", rev = "7ea683975f0069776c74342f326ecfa001cc1a73", features = ["fdb-7_4"] }
thiserror = "2.0.12"


[dependencies]
bincode = "2.0.1"
foundationdb = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread", "time"] }
async-trait = "0.1.88"
