[package]
name = "cabinet-simulation"
version = "0.1.0"
edition = "2024"

[lib]
name = "cabinet"
crate-type = ["cdylib"]

[dependencies]
foundationdb-simulation = { workspace = true }
foundationdb = { workspace = true }
thiserror = { workspace = true }
cabinet = { path = ".." }

